name: Publish Package to npmjs

on:
  release:
    types: [published]

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      
      - name: Use Bun.js
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - run: bun install
      - run: bun run build
        # FIXME: Bun and typescript seems to have some configuration issues,
        # types are emitted correctly but the build fails with a typescript error.
        continue-on-error: true

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: latest
          registry-url: "https://registry.npmjs.org"

      - run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
